### ISSUE TITLE
Make parameter type easier to filter

### ISSUE THREAD

**Issue by pratikunterwegs** [mrc-ide/epireview#26] opened 2024-03-27 12:11 UTC
The parameter name column `parameter_type` is currently not very easy to filter because some of the names are fairly long which requires users to know the exact name, and introduces the potential for errors in specifying the names.

This issue is to request that the parameter types in the column `parameter_type` be made easier to filter by:
- Shortening the name,
- Replacing spaces with underscores,
- Using lowercase names.

E.g. replace `Human delay - Symptom Onset/Fever to Death` with `onset_to_death`.

**Comment by sangeetabhatia03** [comment] 2024-06-05 10:39
Duplicate of #59

**Closed by sangeetabhatia03** 2024-06-05 10:39 UTC
Labels: duplicate
