### ISSUE TITLE
Data compatibility - Marburg

### ISSUE THREAD

**Issue by ruthmccabe** [mrc-ide/epireview#81] opened 2024-06-11 20:04 UTC
Due to the updates to the database, we need to ensure that the Marburg df (e.g. columns) are updated to reflect the data structure that we have just now. 
We had a discussion about doing this at the end of the project, but then an excellent point was raised that we should do this sooner rather than later before this paper entirely drops out of our mind and while the people involved are all still at Imperial.

**Comment by sangeetabhatia03** [comment] 2024-06-12 10:55
Duplicate of #61

**Comment by ruthmccabe** [comment] 2024-06-12 12:22
Sorry! Shall I delete?

**Comment by sangeetabhatia03** [comment] 2024-06-12 13:01
No apologies needed. I'll close the issue :)
Closing as duplicate of #61

**Closed by sangeetabhatia03** 2024-06-12 13:01 UTC
Labels: duplicate
